### ISSUE TITLE
Analyze PCAP offline

### ISSUE THREAD

**Issue by Mr-Click** [xplico/CapAnalysis#1]
Is it possible to use CapAnalysis on a stand-alone host without Internet connectivity?
If yes, will CapAnalysis fail to generate some data (e.g., GeoIP?) 

best regards,
V

**Comment by gnlcosta** [comment]
Hi Mr-Click,
yes, CapAnalysis can be used also without Internet connectivity. As GeoIP CapAnalysis uses (see credits) the GeoLite database of MaxMind. This DB is a file and so doesn't require Internet connectivity.
The easy way to verify my answer is install CapAnalysis (from .deb packages)  and try it without Internet connectivity.

In the next days we will describe how compile and install CapAnalysis. Before it we have to release the 1.1.2 release of Xplico.

Ciao.
Gianluca

**Comment by Mr-Click** [comment]
Excellent!!
Are you going to put publish also Xplico on github?

best regards,
V

**Comment by gnlcosta** [comment]
Yes.
I was not precise: without Internet connectivity what isn't working perfectly on CapAnalysis is the geographical map because it is based on OpenStreetMap, but also without Internet connectivity it is possible to see the map of countries and their weight (expressed using different colors).
Ciao.
Gianluca
